import logging
import os
from contextlib import contextmanager
from typing import Annotated, Literal

from assemblyline_client import get_client
from fastmcp import FastMCP
from fastmcp.exceptions import AuthorizationError
from fastmcp.server.dependencies import get_http_request
from starlette.requests import Request
from starlette.responses import PlainTextResponse

AL_UI = os.environ.get("AL_UI", "http://localhost:5000")
logger = logging.getLogger(__name__)

CERT_BUNDLE = (
    os.environ.get("MCP_CLIENT_CERT_PATH", "/etc/assemblyline/ssl/mcp/tls.crt"),
    os.environ.get("MCP_CLIENT_KEY_PATH", "/etc/assemblyline/ssl/mcp/tls.key"),
)


@contextmanager
def get_assemblyline_client():
    """Context manager to provide an Assemblyline client with authentication based on the request headers.

    Yields:
        Assemblyline client instance with appropriate authentication.

    Raises:
        AuthorizationError: If neither API key nor OAuth token is provided in the request headers.
    """
    request = get_http_request()
    headers = request.headers
    auth_kwargs = {}
    if "x-apikey" in headers and "x-user" in headers:
        # Use API key authentication
        auth_kwargs = {"apikey": (headers["x-user"], headers["x-apikey"])}
    elif "authorization" in headers:
        # Assume OAuth token is provided in the Authorization header
        token = headers["authorization"].split(" ")[-1]
        auth_kwargs = {"oauth": token}
    else:
        raise AuthorizationError("No API key or authorization token provided in the request headers.")

    yield get_client(
        AL_UI,
        **auth_kwargs,
        verify="/etc/assemblyline/ssl/al_root-ca.crt"
        if os.path.exists("/etc/assemblyline/ssl/al_root-ca.crt")
        else True,
    )


def initialize_server() -> FastMCP:
    """Initialize server with all the tools and endpoints.

    Returns:
        FastMCP: An instance of the FastMCP server with registered tools and endpoints.
    """
    server: FastMCP = FastMCP(name="assemblyline-mcp", version="0")

    ##### BEGIN TOOL DEFINITIONS #####
    @server.tool()
    def hello_world():
        """Minimal MCP tool that confirms the server is online.

        Returns:
            str: A greeting message indicating the server is operational.
        """
        return "Hello from your MCP server!"

    @server.tool(
        name="system_configuration",
        description="Retrieve the system configuration for the current user.",
    )
    def system_configuration() -> dict:
        with get_assemblyline_client() as client:
            """Retrieve the system configuration for the current user."""
            return client.user.whoami()["configuration"]

    @server.tool(
        name="classification_definition",
        description="Retrieve the classification definition for the current user.",
    )
    def classification_definition() -> dict:
        """Retrieve the classification definition for the current user."""
        with get_assemblyline_client() as client:
            return client.user.whoami()["c12nDef"]

    @server.tool(
        name="indexes",
        description="Retrieve the Elasticsearch indexes available to the current user.",
    )
    def indexes() -> dict:
        """Retrieve the Elasticsearch indexes available to the current user."""
        with get_assemblyline_client() as client:
            return client.user.whoami()["indexes"]

    @server.tool(
        name="search",
        description="""
            Perform searches using Lucene queries against an Elasticsearch backend.

            Here is an overview of the available indexes you can search:
            - alert: Contains alert documents generated by the system.
            - file: Contains file metadata and analysis results.
            - result: Contains analysis results for submitted files.
            - submission: Contains information about file submissions.
            - signature: Contains signature data used for detection.
            - heuristic: Contains heuristic analysis data.
            - safelist: Contains safelisting rules and entries for tags and files.
            - badlist: Contains badlisting rules and entries for tags and files.

            If you need help evaluating or constructing a Lucene query, consult `classification_definition` for understanding dissemination markings, `indexes` for the database schemas, and `system_configuration` for system settings relative to the user.
            If you're helping build a query for a user, make sure the output is something they can easily copy to their clipboard. I would suggest using backticks to wrap your proposed query with a brief description.

            To help you get started, here is some documentation on Lucene query syntax:
            # Overview
            The search query “mini-language” is used by the Search API. Operators allow you to customize the search -- the available options are explained below.

            # Basic Search
            The search query is parsed into a series of terms and operators. A term can be a single word  like quick, brown or a phrase, surrounded by double quotes "quick brown" which searches for all the words in the phrase, in the same order.

            ## Exemples:
            `"quick brown fox"`
            `quick OR brown OR fox`

            # Fields
            By using basic search, only the default field is searched for the search terms, but it is possible to specify other fields in the query syntax:
            ## Exemples:
             - where the status field contains active: `status:active`
             - where the title field contains quick or brown: `title:(quick OR brown)`
             - where the author field contains the exact phrase "john smith": `author:"John Smith"`
             - where any of the fields book.title, book.content or book.date contains quick or brown (note how we need to escape the * with a backslash): `book.*:(quick OR brown)`

            The Assemblyline datastore is divided in multiple indexes. Each index has the following fields available for searches. Default fields are copied over to the default search field that is used in the case where you only use basic search. Stored field will be returned by the index when issuing a query.
            Important: When using the search engine in the UI, your search query is performed on all these indexes at the same time unless you explicitly specify which index you want to target.

            # Legend
            The special particularities of some field types as well as their various attributes are explained here:
             - `text`: Only the first 4k is indexed, wildcard searches will not work as expected and this field cannot be sorted
             - `ip`: Can be queried using CIDR notation
             - `default`: Queried when no fields are specified
             - `list`: Can have multiple values in the same document
             - `stored`: Returned by default in search results
            """,
        tags={"search", "information retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def search(
        index: Annotated[
            Literal[
                "alert",
                "file",
                "result",
                "submission",
                "signature",
                "heuristic",
                "safelist",
                "badlist",
            ],
            "The Elasticsearch index to search.",
        ],
        query: Annotated[str, "The search query in Lucene syntax."] = "*",
    ) -> dict:
        """Search an Elasticsearch index using a Lucene query."""
        with get_assemblyline_client() as client:
            return getattr(client.search, index)(query=query)

    @server.tool(
        name="facet_search",
        description="Perform a faceted search on a specified index using a Lucene query.",
        tags={"search", "information retrieval", "faceting"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def facet_search(
        index: Annotated[
            Literal[
                "alert",
                "file",
                "result",
                "submission",
                "signature",
                "heuristic",
                "safelist",
                "badlist",
            ],
            "The Elasticsearch index to search.",
        ],
        facet_field: Annotated[str, "The field to facet on."],
        query: Annotated[str, "The search query in Lucene syntax."] = "*",
        facet_size: Annotated[int, "The number of facet results to return."] = 10,
    ) -> dict:
        """Perform a faceted search on a specified index using a Lucene query."""
        with get_assemblyline_client() as client:
            return getattr(client.search.facet, index)(field=facet_field, query=query, size=facet_size)

    @server.tool(
        name="get_alert",
        description="""
            Retrieve detailed information about a specific alert by its ID.
            """,
        tags={"alert", "triage", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_alert(alert_id: str) -> dict:
        """Retrieve alert details by ID."""
        with get_assemblyline_client() as client:
            return client.alert(alert_id)

    @server.tool(
        name="get_submission",
        description="""
            Retrieve detailed information about a specific submission by its ID.
            """,
        tags={"submission", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_submission(submission_id: str) -> dict:
        """Retrieve submission details by ID."""
        with get_assemblyline_client() as client:
            return client.submission(submission_id)

    @server.tool(
        name="file_info",
        description="""
            Retrieve information about a file using its hash.
            """,
        tags={"file", "information"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def file_info(
        file_hash: Annotated[str, "The hash of the file to retrieve information for."],
    ) -> dict:
        """Retrieve file information by its hash."""
        with get_assemblyline_client() as client:
            return client.file(file_hash)

    @server.tool(
        name="file_strings",
        description="""
            Get all the string found in a file by by file sha256
            """,
        tags={"file", "information"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def file_strings(
        file_hash: Annotated[str, "Get all string found in a file by file sha256"],
    ) -> dict:
        """Retrieve file strings by file sha256."""
        with get_assemblyline_client() as client:
            return client.file.strings(file_hash)

    @server.tool(
        name="file_ai_code_analysis",
        description="""
            Perform ai code analysis on the file
            """,
        tags={"file", "information"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def file_ai_code_analysis(
        file_hash: Annotated[str, "Perform ai code analysis on the file"],
    ) -> dict:
        """Perform ai code analysis on the file by file sha256."""
        with get_assemblyline_client() as client:
            return client.file.code_summary(file_hash)

    @server.tool(
        name="get_results",
        description="""
            Retrieve detailed results information given a result cache id
            """,
        tags={"result", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_result(result_id: str) -> dict:
        """Retrieve results details by ID."""
        with get_assemblyline_client() as client:
            return client.result(result_id)

    # @server.tool(name="get_alert_ontology",
    #             description="Get machine friendly json ontologies for a specific alert id",
    #             tags={"ontology", "retrieval"},
    #             meta={"version": "1.0", "author": "cccs-rs"})
    # def get_alert_ontology(alert_id: str) -> List[dict]:
    #     """Retrieve the ontology data based on alert ID."""
    #     data = call_api("GET", f"/ontology/alert/{alert_id}/", download=True)
    #     return_data = []
    #     for line in data.decode('utf-8').splitlines():
    #         return_data.append(json.loads(line))
    #     return return_data

    # @server.tool(name="get_submission_ontology",
    #             description="Get machine friendly json ontologies for a specific submission id",
    #             tags={"ontology", "retrieval"},
    #             meta={"version": "1.0", "author": "cccs-rs"})
    # def get_submission_ontology(submission_id: str) -> List[dict]:
    #     """Retrieve the ontology data based on submission ID."""
    #     data = call_api("GET", f"/ontology/submission/{submission_id}/", download=True)
    #     return_data = []
    #     for line in data.decode('utf-8').splitlines():
    #         return_data.append(json.loads(line))
    #     return return_data

    # @server.tool(name="get_file_ontology",
    #             description="Get machine friendly json ontologies for a specific file hash.",
    #             tags={"ontology", "retrieval"},
    #             meta={"version": "1.0", "author": "cccs-rs"})
    # def get_file_ontology(file_hash: str) -> List[dict]:
    #     """Retrieve the ontology data based on file hash."""
    #     data = call_api("GET", f"/ontology/file/{file_hash}/", download=True)
    #     return_data = []
    #     for line in data.decode('utf-8').splitlines():
    #         return_data.append(json.loads(line))
    #     return return_data

    @server.tool(
        name="get_signature",
        description="""
            Retrieve detailed signature information given a signature id, signature_id must be type_source_name with underscores: {type}_{source}_{name}, if you only have the name, use the search api.
            """,
        tags={"signature", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_signature(signature_id: str) -> dict:
        """Retrieve signature details by ID."""
        with get_assemblyline_client() as client:
            return client.signature(signature_id)

    @server.tool(
        name="get_heuristic",
        description="""
            Retrieve detailed heuristic information given a heuristic id.

            Note: The heuristic ID is of the form: SERVICE.### (e.g., SAMPLERESULT.100)
            """,
        tags={"heuristic", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_heuristic(heuristic_id: str) -> dict:
        """Retrieve heuristic details by ID."""
        with get_assemblyline_client() as client:
            return client.heuristics(heuristic_id)

    @server.tool(
        name="get_safelist",
        description="""
            Retrieve detailed safelist information given a safelist id.
            """,
        tags={"safelist", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_safelist(safelist_id: str) -> dict:
        """Retrieve safelist details by ID."""
        with get_assemblyline_client() as client:
            return client.safelist(safelist_id)

    @server.tool(
        name="get_badlist",
        description="""
            Retrieve detailed badlist information given a badlist id.
            """,
        tags={"badlist", "retrieval"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def get_badlist(badlist_id: str) -> dict:
        """Retrieve badlist details by ID."""
        with get_assemblyline_client() as client:
            return client.badlist(badlist_id)

    @server.tool(
        name="file_tree",
        description="Retrieve the file tree structure for a given submission ID.",
        tags={"file", "submission", "structure"},
        meta={"version": "1.0", "author": "cccs-rs"},
    )
    def file_tree(submission_id: str) -> dict:
        """Retrieve the file tree structure for a given submission ID."""
        with get_assemblyline_client() as client:
            return client.submission.tree(submission_id)

    ##### END TOOL DEFINITIONS #####

    return server


if __name__ == "__main__":
    # Initialize FastMCP instance
    server: FastMCP = initialize_server()
    logger.debug("MCP tools registered...")

    ##### ADD CUSTOM ENDPOINTS HERE #####
    # Health endpoint
    @server.custom_route("/health", methods=["GET"])
    async def health_check(request: Request) -> PlainTextResponse:
        """Health check endpoint for monitoring and liveness probes."""
        return PlainTextResponse("OK")

    """
    Example: Response caching middleware. Will cache responses from the backend API with a default TTL of 1 hour.
            You can manually include/exclude tools.

    from fastmcp.server.middleware.caching import CallToolSettings, ResponseCachingMiddleware

    logger.debug("Adding response caching middleware...")
    server.add_middleware(ResponseCachingMiddleware(
        call_tool_settings=CallToolSettings(
            excluded_tools=[

            ],
        )
    ))
    """

    # Configure Uvicorn relative to the deployment environment
    uvicorn_config = {}
    if all(os.path.exists(fp) for fp in CERT_BUNDLE):
        uvicorn_config.update({"ssl_certfile": CERT_BUNDLE[0], "ssl_keyfile": CERT_BUNDLE[1]})

    # Setup complete, start the server
    logger.debug("Assemblyline MCP server initialization complete")
    server.run(
        transport="http",
        path="/mcp/",
        host="0.0.0.0",
        port=8000,
        show_banner=False,
        uvicorn_config=uvicorn_config,
        stateless_http=True,
    )
